steps:
#First Clone from Google Cloud Source Repository  
- name: 'gcr.io/aerial-ceremony-283410/git'
  args: ['clone','https://source.developers.google.com/p/${_PROJECT}/r/${_REPO_NAME}']

#Build the image 
- name: 'gcr.io/aerial-ceremony-283410/docker'
  args: ['build','-t','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}','.']

#Push the image  
- name: 'gcr.io/aerial-ceremony-283410/docker'
  args: ['push','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}']
  
#Update the container image using kubectl set
- name: 'gcr.io/aerial-ceremony-283410/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/${_DEPLOYMENTNAME}'
  - '${_CONTAINERNAME}=gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
  
substitutions:
    #GCP Specific configuration. Please DON'T change anything
    _PROJECT: aerial-ceremony-283410
    _ZONE: us-central1-c #asia-south1-a
    _GKE_CLUSTER: umesh-gke-sample
    
    #Repository Specific configuration. DevOps can change this settings
    _DEPLOYMENTNAME: nginx-1
    _CONTAINERNAME: nginx-1  
    _REPO_NAME: umesh-gke-sample
    
    # Developers ONLY change
    _VERSION: v2.0.2
    
options:
    substitution_option: 'ALLOW_LOOSE'

