apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-app
        image: nginx:lastest
        ports:
        - name: http-port
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app
spec:
  ports:
  - port: 31010
    nodePort: 31010
    targetPort: http-port
    protocol: TCP
  selector:
    app: nginx-app
  type: NodePort
  # type: LoadBalancer  #[based on requierment] 
